---
title: "Data cleaning, solutions"
author: "RT"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data cleaning, solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Base R data cleaning 

```{r}
Sys.setlocale("LC_TIME", "English")

messy_data <- read.delim("../inst/extdata/messy_data.txt", stringsAsFactors = F)

messy_data$Patient.id <- toupper(messy_data$Patient.id)
messy_data$Patient.id <- gsub("TCGA ", "TCGA_", messy_data$Patient.id)
messy_data <- messy_data[1:18,]
messy_data <- messy_data[,colnames(messy_data)!="X"]



summary(messy_data)
#help: https://www.stat.berkeley.edu/~s133/dates.html
messy_data$Date.of.surgery <- as.Date(messy_data$Date.of.surgery, format="%d-%b-%y")
messy_data$Date.of.birth <- as.Date(as.Date( messy_data$Date.of.birth, format="%d/%m/%Y"))
messy_data$Date.of.diagnosis <- as.Date(messy_data$Date.of.diagnosis, format="%d/%m/%Y")
messy_data$Time.of.death <- as.Date(messy_data$Time.of.death, format="%d-%b-%y")


Age <- difftime(messy_data$Date.of.diagnosis,messy_data$Date.of.birth, units = "days")
Age <- round(Age/365, digits = 0)
table(Age,messy_data$Age)
messy_data$Age <- Age

messy_data$Gender
messy_data$Status

table(messy_data$Status, messy_data$Censor)
messy_data$Identifier <- NULL
messy_data$Classification <- NULL

summary(messy_data$enzyme.level)
boxplot(messy_data$enzyme.level)
messy_data$enzyme.level[messy_data$enzyme.level>600] <- NA
boxplot(messy_data$enzyme.level)
table(messy_data$Histological.subtype)
messy_data$Histological.subtype <- gsub(" ", "", messy_data$Histological.subtype)
table(messy_data$Histological.subtype)

table(messy_data$MUC1)

messy_data$MUC1 <- factor(messy_data$MUC1, levels = c("0", "0bis1", "1", "2", "3"))
messy_data$N <- gsub("(T[[:digit:]])(N[[:digit:]])(M[[:digit:]])", "\\2", messy_data$TNM)
messy_data$M <- gsub("(T[[:digit:]])(N[[:digit:]])(M[[:digit:]])", "\\3", messy_data$TNM)
messy_data$TNM <- NULL
```

# Data cleaning, tidyverse

```{r}
library(tidyverse)
library(readxl)
library(janitor)

messy_data <- read_excel("../inst/extdata/messy_data.xlsx")

messy_data <- read_excel("../inst/extdata/messy_data.xlsx", n_max = 18)

messy_data <- messy_data %>% 
  select_all(~gsub(" ", ".", .)) %>%
  clean_names() %>% 
  remove_empty( which = c("rows","cols"))
  

messy_data <- messy_data %>%
  mutate(patient_id=toupper(patient_id)) %>%
  mutate(patient_id=gsub(" ", "_", patient_id), 
         age=round(as.numeric((date_of_diagnosis-date_of_birth)/365), digits = 0),
         N=substr(tnm, 3, 4), 
         M=substr(tnm, 5, 6), 
         tnm=NULL) %>% 
         mutate(enzyme_level=ifelse(enzyme_level>600, NA, enzyme_level))



```

